---
- name: A simple playbook to copy a file and restart a service
  hosts: dynatrace
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
    - name: Restart service
      ansible.builtin.service:
        name: httpd
        state: restarted
