---
- name: Playbook with random tests
  hosts: datadog.shadowman.dev
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: files/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
